(()=>{'use strict';const C=window.TankCore,canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s),W=960,H=600;
let state='menu',last=0,keys={},tanks=[],shells=[],particles=[],flashes=[],walls=[],scores=[0,0],round=1,countdown=0,roundReset=0,shake=0,audio,layoutIndex=-1,playerCount=1;
function tone(f,d=.06,type='square',vol=.035){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function tank(id,x,y,a,color){return{id,x,y,a,color,r:20,speed:0,cool:0,alive:true,brain:.3,side:Math.random()<.5?-1:1}}
function start(){scores=[0,0];round=1;$('.panel:not(.hidden)')?.classList.add('hidden');$('#hud').classList.remove('hidden');$('#pauseBtn').classList.remove('hidden');$('#p2label').textContent=playerCount===1?'AI TANK':'PLAYER 2';newRound();updateHud()}
function newRound(){do{layoutIndex=(Math.random()*C.layouts.length)|0}while(layoutIndex===newRound.last&&C.layouts.length>1);newRound.last=layoutIndex;walls=C.layouts[layoutIndex].map(x=>({...x}));tanks=[tank(0,105,H/2,0,'#a8d34f'),tank(1,W-105,H/2,Math.PI,'#ff8b3d')];shells=[];particles=[];flashes=[];countdown=3.15;roundReset=0;state='countdown';showCount('3')}
function showCount(text){const e=$('#countdown');e.textContent=text;e.style.opacity='1';setTimeout(()=>e.style.opacity='0',650)}
function wallList(){return[{x:0,y:0,w:W,h:34},{x:0,y:H-34,w:W,h:34},{x:0,y:0,w:34,h:H},{x:W-34,y:0,w:34,h:H},...walls]}
function moveTank(t,dt,forward,back,left,right){if(!t.alive)return;t.a+=(right-left)*2.65*dt;const drive=forward-back,step=drive*145*dt,candidate={...t,x:t.x+Math.cos(t.a)*step,y:t.y+Math.sin(t.a)*step};if(!C.blocked(candidate,wallList(),tanks[1-t.id])){t.x=candidate.x;t.y=candidate.y}t.cool=Math.max(0,t.cool-dt)}
function updateAi(dt){const ai=tanks[1],target=tanks[0];if(!ai.alive||!target.alive)return;ai.brain-=dt;if(ai.brain<=0){ai.brain=.7+Math.random()*.8;ai.side=Math.random()<.5?-1:1}const direct=Math.atan2(target.y-ai.y,target.x-ai.x),clear=!C.lineBlocked(ai,target,wallList()),desired=direct+(clear?0:ai.side*.85),delta=C.angleDelta(ai.a,desired),turn=Math.abs(delta)>.08,forward=Math.abs(delta)<(clear?.65:1.25);moveTank(ai,dt,+forward,0,+(turn&&delta<0),+(turn&&delta>0));if((clear&&Math.abs(delta)<.13)||(!clear&&Math.abs(delta)<.06&&Math.random()<dt*.7))fire(ai)}
function fire(t){if(state!=='playing'||!t.alive||t.cool>0||shells.filter(s=>s.owner===t.id).length>=3)return;t.cool=.48;const x=t.x+Math.cos(t.a)*29,y=t.y+Math.sin(t.a)*29;shells.push({x,y,px:x,py:y,vx:Math.cos(t.a)*310,vy:Math.sin(t.a)*310,r:4,owner:t.id,life:5,bounces:0,armed:.16});flashes.push({x,y,a:t.a,life:.1});tone(t.id?290:360,.07)}
function explodeTank(t,owner){if(!t.alive)return;t.alive=false;scores[owner]++;shake=14;for(let i=0;i<42;i++){const a=Math.random()*Math.PI*2,s=40+Math.random()*230;particles.push({x:t.x,y:t.y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.4+Math.random()*.8,color:i%3?t.color:'#f5e7b2'})}tone(55,.45,'sawtooth',.075);$('#roundFlash').animate([{opacity:.7},{opacity:0}],{duration:260});updateHud();roundReset=1.65;state='roundover'}
function update(dt){if(state==='countdown'){const before=Math.ceil(countdown),previous=countdown;countdown-=dt;const after=Math.ceil(countdown);if(after!==before&&after>0)showCount(String(after));if(previous>.45&&countdown<=.45)showCount('DUEL!');if(countdown<=0){state='playing';$('#countdown').style.opacity='0';tone(520,.09)}return}if(state==='roundover'){roundReset-=dt;updateEffects(dt);if(roundReset<=0){if(scores[0]>=5||scores[1]>=5)showWinner();else{round++;newRound();updateHud()}}return}if(state!=='playing')return;
moveTank(tanks[0],dt,+!!keys.w,+!!keys.s,+!!keys.a,+!!keys.d);if(playerCount===1)updateAi(dt);else moveTank(tanks[1],dt,+!!keys.ArrowUp,+!!keys.ArrowDown,+!!keys.ArrowLeft,+!!keys.ArrowRight);
for(const s of shells){s.px=s.x;s.py=s.y;s.armed-=dt;s.life-=dt;let nx=s.x+s.vx*dt,ny=s.y+s.vy*dt;const probe={...s,vx:s.vx*dt,vy:s.vy*dt};for(const wall of wallList()){const hit=C.shellWallHit(probe,wall);if(hit){if(hit.vx!==probe.vx){s.vx=-s.vx;nx=s.x+s.vx*dt}else{s.vy=-s.vy;ny=s.y+s.vy*dt}s.bounces++;s.life-=.25;tone(170+s.bounces*25,.025,'square',.018);break}}s.x=nx;s.y=ny;if(s.armed<=0)for(const t of tanks)if(t.alive&&C.circleCircle(s,t)){s.life=0;explodeTank(t,s.owner);break}}shells=shells.filter(s=>s.life>0&&s.bounces<=5);updateEffects(dt);shake*=Math.pow(.04,dt)}
function updateEffects(dt){for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.97;p.vy*=.97;p.life-=dt}particles=particles.filter(p=>p.life>0);for(const f of flashes)f.life-=dt;flashes=flashes.filter(f=>f.life>0)}
function draw(){ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,W,H);ctx.save();if(shake>1)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);ctx.fillStyle='#151a12';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#20281b';ctx.lineWidth=1;for(let x=0;x<W;x+=24){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=24){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(const w of wallList()){ctx.fillStyle='#444a39';ctx.fillRect(w.x,w.y,w.w,w.h);ctx.strokeStyle='#727963';ctx.lineWidth=3;ctx.strokeRect(w.x+2,w.y+2,w.w-4,w.h-4);ctx.strokeStyle='#2a2e23';for(let x=w.x+10;x<w.x+w.w;x+=18){ctx.beginPath();ctx.moveTo(x,w.y+4);ctx.lineTo(x,w.y+w.h-4);ctx.stroke()}}
for(const s of shells){ctx.strokeStyle=s.owner?'#ff8b3d88':'#a8d34f88';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(s.px,s.py);ctx.lineTo(s.x,s.y);ctx.stroke();ctx.fillStyle='#fff3bd';ctx.fillRect(s.x-3,s.y-3,6,6)}for(const f of flashes){ctx.save();ctx.translate(f.x,f.y);ctx.rotate(f.a);ctx.fillStyle='#fff1a6';ctx.beginPath();ctx.moveTo(0,-9);ctx.lineTo(20,0);ctx.lineTo(0,9);ctx.fill();ctx.restore()}
for(const t of tanks)if(t.alive)drawTank(t);for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.fillRect(p.x-3,p.y-3,6,6)}ctx.globalAlpha=1;ctx.restore()}
function drawTank(t){ctx.save();ctx.translate(t.x,t.y);ctx.rotate(t.a);ctx.fillStyle='#080a07';ctx.fillRect(-23,-20,46,8);ctx.fillRect(-23,12,46,8);ctx.fillStyle=t.color;ctx.fillRect(-18,-15,36,30);ctx.strokeStyle='#f5e7b2';ctx.lineWidth=2;ctx.strokeRect(-18,-15,36,30);ctx.fillStyle='#24291f';ctx.beginPath();ctx.arc(0,0,11,0,Math.PI*2);ctx.fill();ctx.strokeStyle=t.color;ctx.stroke();ctx.fillStyle=t.color;ctx.fillRect(3,-4,29,8);ctx.restore()}
function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function updateHud(){$('#p1score').textContent=scores[0];$('#p2score').textContent=scores[1];$('#round').textContent=round}
function pause(){if(!['playing','countdown'].includes(state))return;state='paused';$('#paused').classList.remove('hidden')}function resume(){if(state!=='paused')return;state=countdown>0?'countdown':'playing';$('#paused').classList.add('hidden');last=performance.now()}
function showWinner(){state='winner';$('#hud').classList.add('hidden');$('#pauseBtn').classList.add('hidden');const winner=scores[0]>=5?'PLAYER 1':playerCount===1?'AI TANK':'PLAYER 2';$('#winnerTitle').textContent=`${winner} WINS`;$('#winnerTitle').style.color=scores[0]>=5?'#a8d34f':'#ff8b3d';$('#winnerScore').textContent=`${scores[0]} — ${scores[1]}`;$('#winner').classList.remove('hidden');[440,550,660,880].forEach((f,i)=>setTimeout(()=>tone(f,.12),i*100))}
addEventListener('keydown',e=>{if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter'].includes(e.key))e.preventDefault();keys[e.key]=true;keys[e.key.toLowerCase()]=true;if(e.code==='Space'&&!e.repeat)fire(tanks[0]);if(playerCount===2&&e.key==='Enter'&&!e.repeat)fire(tanks[1]);if(e.key.toLowerCase()==='p')state==='paused'?resume():pause()});addEventListener('keyup',e=>{keys[e.key]=false;keys[e.key.toLowerCase()]=false});
for(const button of document.querySelectorAll('[data-players]'))button.onclick=()=>{playerCount=+button.dataset.players;document.querySelectorAll('[data-players]').forEach(b=>b.classList.toggle('selected',b===button));$('#opponentLabel').textContent=playerCount===1?'AI OPPONENT':'PLAYER 2';$('#opponentKeys').innerHTML=playerCount===1?'AUTOMATIC MAZE COMBAT':'↑/↓ MOVE · ←/→ TURN<br>ENTER FIRE'};
$('#start').onclick=start;$('#restart').onclick=start;$('#restartPause').onclick=start;$('#pauseBtn').onclick=pause;$('#resume').onclick=resume;draw();})();
