(()=>{'use strict';const C=window.VectorCore,canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s),W=960,H=600,WORLD=650;let state='menu',player,enemies,shots,particles,rocks,score,wave,spawnLeft,last=0,keys={},audio,flash=0,shake=0;
function tone(f,d=.08,type='square',v=.035){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function makeRocks(){return Array.from({length:42},(_,i)=>{const a=Math.random()*Math.PI*2,r=90+Math.random()*520;return{x:Math.cos(a)*r,z:Math.sin(a)*r,size:5+Math.random()*18,type:i%4?'pyramid':'block'}})}
function reset(){player={x:0,z:0,a:0,lives:3,cool:0,inv:0};enemies=[];shots=[];particles=[];rocks=makeRocks();score=0;wave=1;spawnLeft=3;state='playing';$('.panel:not(.hidden)')?.classList.add('hidden');$('#hud').classList.remove('hidden');$('#pause').classList.remove('hidden');$('#touch').classList.remove('hidden');spawnWave();hud();alertMsg('WAVE 1')}
function spawnWave(){const count=wave+2;spawnLeft=count;for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,r=260+Math.random()*260;enemies.push({x:player.x+Math.cos(a)*r,z:player.z+Math.sin(a)*r,a:a+Math.PI,health:wave>2&&i%4===0?2:1,cool:1+Math.random()*2,speed:18+wave*2,turn:Math.random()-.5,alive:true})}}
function alertMsg(s){const e=$('#alert');e.textContent=s;e.animate([{opacity:1},{opacity:1,offset:.55},{opacity:0}],{duration:1500,fill:'forwards'})}
function fire(owner){if(state!=='playing'||owner.cool>0)return;owner.cool=owner===player?.3:1.2+Math.random()*.7;shots.push({x:owner.x+Math.sin(owner.a)*10,z:owner.z+Math.cos(owner.a)*10,a:owner.a,owner,life:2.4});tone(owner===player?390:110,.08,owner===player?'square':'sawtooth',.045)}
function damage(){if(player.inv>0)return;player.lives--;player.inv=2;flash=1;shake=18;tone(48,.5,'sawtooth',.08);alertMsg(player.lives?'ARMOUR HIT':'TANK DESTROYED');hud();if(player.lives<=0)setTimeout(end,900)}
function end(){state='gameover';$('#hud').classList.add('hidden');$('#pause').classList.add('hidden');$('#touch').classList.add('hidden');$('#final').textContent=`SCORE ${String(score).padStart(5,'0')} · WAVE ${wave}`;$('#gameover').classList.remove('hidden')}
function update(dt){if(state!=='playing')return;player.cool=Math.max(0,player.cool-dt);player.inv=Math.max(0,player.inv-dt);const turn=(keys.right?1:0)-(keys.left?1:0),drive=(keys.forward?1:0)-(keys.back?1:0);player.a=C.wrapAngle(player.a+turn*1.55*dt);const speed=drive*(drive<0?48:76);player.x+=Math.sin(player.a)*speed*dt;player.z+=Math.cos(player.a)*speed*dt;C.clampWorld(player,WORLD);
for(const e of enemies){e.cool-=dt;const target=Math.atan2(player.x-e.x,player.z-e.z),d=C.angleDelta(e.a,target),dist=C.distance(e,player);e.a=C.wrapAngle(e.a+Math.sign(d)*Math.min(Math.abs(d),.75*dt));if(dist>95){e.x+=Math.sin(e.a)*e.speed*dt;e.z+=Math.cos(e.a)*e.speed*dt}if(dist<340&&Math.abs(d)<.16&&e.cool<=0)fire(e);if(dist<25)damage()}
for(const s of shots){s.x+=Math.sin(s.a)*245*dt;s.z+=Math.cos(s.a)*245*dt;s.life-=dt;if(s.owner===player){for(const e of enemies)if(e.alive&&C.hitCircle(s,e,15)){s.life=0;e.health--;if(e.health<=0){e.alive=false;score+=100*wave;explode(e);tone(70,.25,'sawtooth',.06)}break}}else if(C.hitCircle(s,player,12)){s.life=0;damage()}}
shots=shots.filter(s=>s.life>0);enemies=enemies.filter(e=>e.alive);for(const p of particles){p.x+=p.vx*dt;p.z+=p.vz*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);if(!enemies.length){wave++;spawnWave();player.lives=Math.min(3,player.lives+1);hud();alertMsg(`WAVE ${wave}`)}flash=Math.max(0,flash-dt*2);shake*=Math.pow(.03,dt)}
function explode(e){shake=10;for(let i=0;i<20;i++)particles.push({x:e.x,z:e.z,vx:(Math.random()-.5)*70,vz:(Math.random()-.5)*70,life:.4+Math.random()*.7})}
function hud(){$('#score').textContent=String(score).padStart(5,'0');$('#wave').textContent=wave;$('#lives').textContent='◆'.repeat(Math.max(0,player.lives))}
function line3(a,b,color='#53ff72',width=2){const p=C.project(a,player,W,H),q=C.project(b,player,W,H);if(!p||!q)return;ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}
function drawGrid(){ctx.strokeStyle='#0c4a20';ctx.lineWidth=1;for(let i=-600;i<=600;i+=50){line3({x:i,y:0,z:-600},{x:i,y:0,z:600},'#0b461d',1);line3({x:-600,y:0,z:i},{x:600,y:0,z:i},'#0b461d',1)}ctx.strokeStyle='#32d757';ctx.beginPath();ctx.moveTo(0,H*.54);ctx.lineTo(W,H*.54);ctx.stroke()}
function wireObject(o,color='#68ff7d'){const p=C.project({x:o.x,y:0,z:o.z},player,W,H);if(!p||p.depth>600)return;const s=Math.max(2,(o.size||14)*p.scale),base=p.y;if(o.type==='pyramid'){line3({x:o.x-o.size,y:0,z:o.z-o.size},{x:o.x,y:o.size*1.5,z:o.z},color);line3({x:o.x+o.size,y:0,z:o.z-o.size},{x:o.x,y:o.size*1.5,z:o.z},color);line3({x:o.x-o.size,y:0,z:o.z+o.size},{x:o.x,y:o.size*1.5,z:o.z},color);line3({x:o.x+o.size,y:0,z:o.z+o.size},{x:o.x,y:o.size*1.5,z:o.z},color)}else{ctx.strokeStyle=color;ctx.strokeRect(p.x-s/2,base-s,s,s)}}
function drawEnemy(e){const p=C.project({x:e.x,y:0,z:e.z},player,W,H);if(!p||p.depth>580)return;const s=Math.max(5,20*p.scale);ctx.strokeStyle='#ff4e4e';ctx.lineWidth=Math.max(1,2*p.scale);ctx.strokeRect(p.x-s, p.y-s*.65,s*2,s*.55);ctx.beginPath();ctx.ellipse(p.x,p.y-s*.75,s*.55,s*.3,0,0,Math.PI*2);ctx.stroke();const barrel=16*p.scale;ctx.beginPath();ctx.moveTo(p.x,p.y-s*.78);ctx.lineTo(p.x+Math.sin(e.a-player.a)*barrel,p.y-s*.78);ctx.stroke()}
function drawRadar(){const x=82,y=90,r=56;ctx.strokeStyle='#42ff65';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(x-r,y);ctx.lineTo(x+r,y);ctx.moveTo(x,y-r);ctx.lineTo(x,y+r);ctx.stroke();for(const e of enemies){const dx=e.x-player.x,dz=e.z-player.z,s=Math.sin(-player.a),c=Math.cos(-player.a),rx=(dx*c-dz*s)/7,ry=-(dx*s+dz*c)/7;if(rx*rx+ry*ry<r*r){ctx.fillStyle='#ff4e4e';ctx.fillRect(x+rx-2,y+ry-2,5,5)}}}
function draw(){ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#010603';ctx.fillRect(0,0,W,H);ctx.save();if(shake>1)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawGrid();const visible=[...rocks,...enemies].sort((a,b)=>C.distance(b,player)-C.distance(a,player));for(const o of visible)o.health?drawEnemy(o):wireObject(o);for(const s of shots){const p=C.project({x:s.x,y:7,z:s.z},player,W,H);if(p){ctx.fillStyle=s.owner===player?'#d8ff96':'#ff5959';ctx.fillRect(p.x-3,p.y-3,6,6)}}for(const p of particles)wireObject({...p,size:2,type:'block'},'#ffb14a');drawRadar();ctx.strokeStyle='#90ffa0';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(W/2-24,H/2);ctx.lineTo(W/2-7,H/2);ctx.moveTo(W/2+7,H/2);ctx.lineTo(W/2+24,H/2);ctx.moveTo(W/2,H/2-18);ctx.lineTo(W/2,H/2-6);ctx.stroke();if(player&&player.inv>0&&Math.floor(player.inv*8)%2===0){ctx.fillStyle='#ffffff16';ctx.fillRect(0,0,W,H)}ctx.restore();if(flash){ctx.fillStyle=`rgba(255,0,0,${flash*.28})`;ctx.fillRect(0,0,W,H)}}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function pause(){if(state!=='playing')return;state='paused';$('#paused').classList.remove('hidden')}function resume(){if(state!=='paused')return;state='playing';$('#paused').classList.add('hidden');last=performance.now()}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(k==='w'||k==='arrowup')keys.forward=true;if(k==='s'||k==='arrowdown')keys.back=true;if(k==='a'||k==='arrowleft')keys.left=true;if(k==='d'||k==='arrowright')keys.right=true;if(e.code==='Space'&&!e.repeat)fire(player);if(k==='p')state==='paused'?resume():pause()});addEventListener('keyup',e=>{const k=e.key.toLowerCase();if(k==='w'||k==='arrowup')keys.forward=false;if(k==='s'||k==='arrowdown')keys.back=false;if(k==='a'||k==='arrowleft')keys.left=false;if(k==='d'||k==='arrowright')keys.right=false});
for(const b of document.querySelectorAll('#touch button')){const k=b.dataset.key,on=e=>{e.preventDefault();if(k==='fire')fire(player);else keys[k]=true},off=e=>{e.preventDefault();if(k!=='fire')keys[k]=false};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off)}$('#start').onclick=reset;$('#restart').onclick=reset;$('#pause').onclick=pause;$('#resume').onclick=resume;draw()})();
