(()=>{'use strict';
const C=window.SliderCore,canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),map=document.querySelector('#map'),mctx=map.getContext('2d');
const $=s=>document.querySelector(s),WORLD=5200,FOOD_TARGET=650,BOT_COUNT=18,skins=['#62f6d0','#ff5e8a','#ffd25f','#7b73ff','#58b7ff','#ff8d4d'];
const names=['Vortex','Nova','Pixel','Glitch','Comet','Hex','Orbit','Dash','Echo','Flux','Ziggy','Quasar','Bolt','Ion','Prism','Rift','Jinx','Cosmo'];
let dpr=1,w=0,h=0,state='menu',player=null,snakes=[],foods=[],particles=[],pointer={x:0,y:0,down:false},keys={},camera={x:WORLD/2,y:WORLD/2,zoom:1},last=0,skin=+(localStorage.sliderSkin||0),audio=null,muted=localStorage.sliderMuted==='1',gameMode=localStorage.sliderMode||'classic',ending=false;
function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
skins.forEach((c,i)=>{const b=document.createElement('button');b.className='skin'+(i===skin?' selected':'');b.style.setProperty('--skin',c);b.setAttribute('aria-label','Skin '+(i+1));b.onclick=()=>{skin=i;localStorage.sliderSkin=i;document.querySelectorAll('.skin').forEach((x,j)=>x.classList.toggle('selected',j===i));tone(350,.05)};$('#skins').append(b)});$('#name').value=localStorage.sliderName||'';
function tone(freq,d=.04){if(muted)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function makeSnake(id,name,color,x,y,isBot){const a=Math.random()*C.TAU,points=[];for(let i=0;i<34;i++)points.push({x:x-Math.cos(a)*i*7,y:y-Math.sin(a)*i*7});return{id,name,color,x,y,a,target:a,speed:150,score:34,points,isBot,alive:true,boost:false,think:0,targetFood:null}}
function addFood(x=Math.random()*WORLD,y=Math.random()*WORLD,value=1,color=skins[Math.random()*skins.length|0]){foods.push({x,y,value,color,pulse:Math.random()*C.TAU})}
function start(){localStorage.sliderName=$('#name').value.trim()||'Slider';localStorage.sliderMode=gameMode;ending=false;for(const c of 'menu gameover paused'.split(' '))$('#'+c).classList.add('hidden');$('#hud').classList.remove('hidden');$('#modeBadge').textContent=gameMode==='knockout'?'KNOCKOUT':'CLASSIC';$('#modeBadge').classList.remove('elite');foods=[];particles=[];snakes=[];for(let i=0;i<FOOD_TARGET;i++)addFood();player=makeSnake('you',localStorage.sliderName,skins[skin],WORLD/2,WORLD/2,false);snakes.push(player);for(let i=0;i<BOT_COUNT;i++){const s=makeSnake('b'+i,names[i],skins[(i+1)%skins.length],400+Math.random()*(WORLD-800),400+Math.random()*(WORLD-800),true);s.score=45+Math.random()*120;s.points=Array.from({length:s.score|0},(_,j)=>({x:s.x-Math.cos(s.a)*j*7,y:s.y-Math.sin(s.a)*j*7}));snakes.push(s)}camera.x=player.x;camera.y=player.y;state='playing';last=performance.now();tone(520,.09)}
function targetFor(s){if(!s.isBot){let dx=pointer.x-w/2,dy=pointer.y-h/2;if(keys.ArrowLeft||keys.a)dx=-200;if(keys.ArrowRight||keys.d)dx=200;if(keys.ArrowUp||keys.w)dy=-200;if(keys.ArrowDown||keys.s)dy=200;if(dx||dy)s.target=Math.atan2(dy,dx);s.boost=(pointer.down||keys[' ']||keys.Shift)&&s.score>38;return}const alive=snakes.filter(x=>x.alive).length,level=gameMode==='knockout'?C.aiLevel(alive):1;s.think-=1/60;if(s.think<=0){s.think=(.28+Math.random()*.42)/level;let best=null,bd=Infinity;if(level===3){for(const rival of snakes){if(rival===s||!rival.alive)continue;const d=C.dist2(s,rival);if(d<bd&&rival.score<s.score*1.35){bd=d;best=rival}}}if(!best){for(const f of foods){const d=C.dist2(s,f);if(d<bd){bd=d;best=f}}}s.targetFood=best;if(best)s.target=Math.atan2(best.y-s.y,best.x-s.x);const edge=300+level*45;if(s.x<edge)s.target=0;if(s.x>WORLD-edge)s.target=Math.PI;if(s.y<edge)s.target=Math.PI/2;if(s.y>WORLD-edge)s.target=-Math.PI/2;s.target+=((Math.random()-.5)*(.5/level));s.boost=Math.random()<(.035*level)&&s.score>45}}
function finish(won=false){if(ending)return;ending=true;state=won?'won':'dead';setTimeout(()=>{const score=player.score|0,best=Math.max(score,+(localStorage.sliderBest||0));localStorage.sliderBest=best;$('#finalScore').textContent=score;$('#best').textContent='Best: '+best;$('#resultLabel').textContent=won?'GRID CONQUERED':'SIGNAL LOST';$('#resultCaption').textContent=won?'knockout champion':'final length';$('#hud').classList.add('hidden');$('#gameover').classList.remove('hidden');tone(won?760:90,won?.25:.4)},650)}
function kill(s){if(!s.alive)return;s.alive=false;for(let i=3;i<s.points.length;i+=2)addFood(s.points[i].x,s.points[i].y,2,s.color);for(let i=0;i<25;i++)particles.push({x:s.x,y:s.y,vx:(Math.random()-.5)*240,vy:(Math.random()-.5)*240,life:1,color:s.color});if(s===player){finish(false)}else if(gameMode==='classic')setTimeout(()=>{if(state==='playing'){const n=makeSnake(s.id,s.name,s.color,400+Math.random()*(WORLD-800),400+Math.random()*(WORLD-800),true);snakes[snakes.indexOf(s)]=n}},1800)}
function update(dt){if(state!=='playing')return;for(const s of snakes){if(!s.alive)continue;targetFor(s);const baseTurn=2.5-Math.min(s.score,220)*.004,alive=snakes.filter(x=>x.alive).length,aiBoost=s.isBot&&gameMode==='knockout'?1+(C.aiLevel(alive)-1)*.18:1,turn=baseTurn*(s.isBot?aiBoost:1.65);s.a=C.lerpAngle(s.a,s.target,turn*dt);const boost=s.boost&&s.score>38;s.speed=150+(boost?100:0);s.x+=Math.cos(s.a)*s.speed*dt;s.y+=Math.sin(s.a)*s.speed*dt;s.x=C.clamp(s.x,10,WORLD-10);s.y=C.clamp(s.y,10,WORLD-10);s.points.unshift({x:s.x,y:s.y});const max=Math.max(28,s.score|0);while(s.points.length>max)s.points.pop();if(boost&&Math.random()<dt*16){s.score-=.12;const tail=s.points[s.points.length-1];if(tail)addFood(tail.x,tail.y,.25,s.color)}for(let i=foods.length-1;i>=0;i--){if(C.dist2(s,foods[i])<420){const f=foods[i];foods.splice(i,1);s.score+=f.value;particles.push({x:f.x,y:f.y,vx:0,vy:0,life:.45,color:f.color});if(s===player&&Math.random()<.18)tone(650+Math.random()*220,.025)}}for(const other of snakes){if(other===s||!other.alive)continue;if(C.collides(s,other.points,10+s.score*.005,6)){kill(s);break}}if(s.x<=11||s.x>=WORLD-11||s.y<=11||s.y>=WORLD-11)kill(s)}while(foods.length<FOOD_TARGET)addFood();for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);if(player){const living=snakes.filter(s=>s.alive);if(gameMode==='knockout'&&player.alive&&living.length===1){finish(true);return}camera.x+=(player.x-camera.x)*Math.min(1,dt*5);camera.y+=(player.y-camera.y)*Math.min(1,dt*5);camera.zoom+=(C.clamp(1.14-player.score/900,.72,1)-(camera.zoom))*dt*2;$('#score').textContent=player.score|0;$('#rank').textContent=player.alive?'#'+C.rank(living,player.id):'—';$('#alive').textContent=living.length;const elite=gameMode==='knockout'&&living.length<=5;$('#modeBadge').classList.toggle('elite',elite);$('#modeBadge').textContent=elite?'FINAL 5 · ELITE AI':gameMode==='knockout'?'KNOCKOUT':'CLASSIC';renderLeaders()}}
function worldToScreen(x,y){return{x:(x-camera.x)*camera.zoom+w/2,y:(y-camera.y)*camera.zoom+h/2}}
function draw(){ctx.clearRect(0,0,w,h);ctx.fillStyle='#070914';ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w/2,h/2);ctx.scale(camera.zoom,camera.zoom);ctx.translate(-camera.x,-camera.y);const left=camera.x-w/camera.zoom/2-80,top=camera.y-h/camera.zoom/2-80,right=camera.x+w/camera.zoom/2+80,bottom=camera.y+h/camera.zoom/2+80;ctx.strokeStyle='#171d36';ctx.lineWidth=1;ctx.beginPath();for(let x=Math.floor(left/100)*100;x<right;x+=100){ctx.moveTo(x,top);ctx.lineTo(x,bottom)}for(let y=Math.floor(top/100)*100;y<bottom;y+=100){ctx.moveTo(left,y);ctx.lineTo(right,y)}ctx.stroke();ctx.strokeStyle='#ff547055';ctx.lineWidth=12;ctx.strokeRect(0,0,WORLD,WORLD);ctx.globalCompositeOperation='lighter';for(const f of foods){if(f.x<left||f.x>right||f.y<top||f.y>bottom)continue;const r=2.8+f.value*1.25+Math.sin(performance.now()*.004+f.pulse);ctx.fillStyle=f.color;ctx.shadowColor=f.color;ctx.shadowBlur=10;ctx.beginPath();ctx.arc(f.x,f.y,r,0,C.TAU);ctx.fill()}ctx.globalCompositeOperation='source-over';ctx.shadowBlur=0;for(const s of snakes.filter(x=>x.alive).sort((a,b)=>a===player?1:b===player?-1:0))drawSnake(s);for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,3+p.life*4,0,C.TAU);ctx.fill()}ctx.globalAlpha=1;ctx.restore();drawMap()}
function drawSnake(s){const width=12+Math.min(s.score,300)*.018;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();for(let i=s.points.length-1;i>=0;i--){const p=s.points[i];if(i===s.points.length-1)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y)}ctx.strokeStyle='#02040b';ctx.lineWidth=width+6;ctx.stroke();ctx.strokeStyle=s.color;ctx.shadowColor=s.color;ctx.shadowBlur=s.boost?18:7;ctx.lineWidth=width;ctx.stroke();ctx.shadowBlur=0;ctx.setLineDash([2,13]);ctx.strokeStyle='#ffffff55';ctx.lineWidth=2;ctx.stroke();ctx.setLineDash([]);const nx=-Math.sin(s.a),ny=Math.cos(s.a),fx=Math.cos(s.a)*4,fy=Math.sin(s.a)*4;for(const side of [-1,1]){ctx.fillStyle='white';ctx.beginPath();ctx.arc(s.x+fx+nx*side*4,s.y+fy+ny*side*4,2.8,0,C.TAU);ctx.fill();ctx.fillStyle='#101426';ctx.beginPath();ctx.arc(s.x+fx*1.5+nx*side*4,s.y+fy*1.5+ny*side*4,1.2,0,C.TAU);ctx.fill()}ctx.fillStyle='#dce3ff';ctx.font='600 12px system-ui';ctx.textAlign='center';ctx.fillText(s.name,s.x,s.y-18)}
function renderLeaders(){const top=[...snakes].filter(s=>s.alive).sort((a,b)=>b.score-a.score).slice(0,8);$('#leaders').innerHTML=top.map(s=>`<li class="${s===player?'me':''}">${escapeHtml(s.name)} <b>${s.score|0}</b></li>`).join('')}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function drawMap(){mctx.clearRect(0,0,150,150);mctx.strokeStyle='#6571a055';mctx.beginPath();mctx.arc(75,75,72,0,C.TAU);mctx.stroke();for(const s of snakes){if(!s.alive)continue;mctx.fillStyle=s===player?'#fff':s.color;mctx.beginPath();mctx.arc(s.x/WORLD*140+5,s.y/WORLD*140+5,s===player?3:1.5,0,C.TAU);mctx.fill()}}
function frame(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt);draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
function pause(toggle=true){if(state==='playing'&&toggle){state='paused';$('#paused').classList.remove('hidden')}else if(state==='paused'){state='playing';$('#paused').classList.add('hidden');last=performance.now()}}
canvas.addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY});canvas.addEventListener('pointerdown',e=>{pointer.down=true;pointer.x=e.clientX;pointer.y=e.clientY});addEventListener('pointerup',()=>pointer.down=false);addEventListener('keydown',e=>{keys[e.key]=true;if(e.key==='p'||e.key==='P'||e.key==='Escape')pause();if(e.key==='m'||e.key==='M'){muted=!muted;localStorage.sliderMuted=muted?'1':'0'}});addEventListener('keyup',e=>keys[e.key]=false);addEventListener('blur',()=>{if(state==='playing')pause()});document.querySelectorAll('.mode').forEach(b=>{b.classList.toggle('selected',b.dataset.mode===gameMode);b.onclick=()=>{gameMode=b.dataset.mode;localStorage.sliderMode=gameMode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('selected',x===b));tone(420,.05)}});$('#play').onclick=start;$('#again').onclick=start;$('#pauseBtn').onclick=()=>pause();$('#resume').onclick=()=>pause(false);$('#name').addEventListener('keydown',e=>{if(e.key==='Enter')start()});
})();
