(()=>{'use strict';const C=window.VectorCore,cv=document.querySelector('#game'),x=cv.getContext('2d'),$=q=>document.querySelector(q),W=960,H=600,SIZE=720,SEED=1980;let state='menu',p,enemies,missiles,shots,fx,obs,score,high=+(localStorage.vectorFrontlineHigh||0),stage,last=0,keys={},audio,shake=0,red=0,lesson=0,lessonTime=0,gpFire=false,dirTimer=0;
function tone(f,d=.08,type='square',v=.03){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function generate(){const r=C.rng(SEED),a=[];for(let i=0;i<38;i++){let o;do{o={x:(r()-.5)*1250,z:(r()-.5)*1250,w:18+r()*45,d:18+r()*45,h:10+r()*45,type:['cube','block','pyramid','wedge','tower'][i%5]}}while(Math.hypot(o.x,o.z)<100);a.push(o)}return a}
function tankAt(dist=320){for(let n=0;n<50;n++){const a=Math.random()*Math.PI*2,e={x:p.x+Math.sin(a)*dist,z:p.z+Math.cos(a)*dist,r:14,a:a+Math.PI};if(!C.blocked(e,obs,SIZE))return e}return{x:300,z:300,r:14,a:Math.PI}}
function beginTraining(){state='training';$('#menu').classList.add('hidden');$('#training').classList.remove('hidden');lesson=0;lessonTime=0;showLesson()}
function showLesson(){const data=[['DRIVE FORWARD','Hold W and Up Arrow together.'],['PIVOT IN PLACE','Hold W and Down Arrow together.'],['FIRE CANNON','Press Space to fire forward.']][lesson];$('#lessonNum').textContent=`${lesson+1}/3`;$('#lessonTitle').textContent=data[0];$('#lessonText').textContent=data[1];$('#trainingBar').style.width='0'}
function reset(){p={x:0,z:0,r:13,a:0,reserve:2,cool:0,inv:0};obs=generate();enemies=[];missiles=[];shots=[];fx=[];score=0;stage=1;dirTimer=3;state='play';document.querySelectorAll('.panel').forEach(e=>e.classList.add('hidden'));$('#hud').classList.remove('hidden');$('#pause').classList.remove('hidden');$('#touch').classList.remove('hidden');spawn();hud();warn('HOSTILE TANK — REAR')}
function spawn(){const count=Math.min(2+Math.floor(stage/3),5);for(let i=0;i<count;i++){const e=Object.assign(tankAt(280+Math.random()*230),{cool:1+Math.random()*2,speed:25+stage*1.1,hp:stage>8&&i%3===0?2:1,type:i%4===3?'heavy':'tank'});enemies.push(e)}if(stage>=3&&stage%2===1){const m=tankAt(410);missiles.push(Object.assign(m,{speed:52+stage*1.4,life:15,type:'missile'}))}}
function hud(){high=Math.max(high,score);localStorage.vectorFrontlineHigh=high;$('#score').textContent=String(score).padStart(5,'0');$('#high').textContent=String(high).padStart(5,'0');$('#lives').textContent='▲'.repeat(p.reserve)}
function warn(s){const e=$('#warning');e.textContent=s;e.animate([{opacity:1},{opacity:1,offset:.65},{opacity:0}],{duration:1300,fill:'forwards'})}
function fire(owner){if(!owner||owner.cool>0||state!=='play')return;owner.cool=owner===p?.34:1.25;shots.push({x:owner.x+Math.sin(owner.a)*18,z:owner.z+Math.cos(owner.a)*18,px:owner.x,pz:owner.z,a:owner.a,owner,life:3});tone(owner===p?430:95,.07,owner===p?'square':'sawtooth',.045)}
function move(e,drive,turn,dt,speed=78){e.a=C.wrapAngle(e.a+turn*2.05*dt);const q={...e,x:e.x+Math.sin(e.a)*drive*speed*dt,z:e.z+Math.cos(e.a)*drive*speed*dt};if(!C.blocked(q,obs,SIZE)){e.x=q.x;e.z=q.z}}
function treadInput(){let l=(keys.lf?1:0)-(keys.lr?1:0),r=(keys.rf?1:0)-(keys.rr?1:0);const g=navigator.getGamepads?.()[0];if(g){l=Math.abs(g.axes[1]||0)>.2?-(g.axes[1]||0):l;r=Math.abs(g.axes[3]||0)>.2?-(g.axes[3]||0):r;const f=g.buttons[0]?.pressed||g.buttons[7]?.pressed;if(f&&!gpFire)fire(p);gpFire=f}return C.treadMotion(l,r)}
function hitPlayer(){if(p.inv>0)return;p.reserve--;p.inv=2;red=1;shake=20;tone(45,.5,'sawtooth',.08);hud();if(p.reserve<0){state='over';setTimeout(gameOver,700)}else{warn('RESERVE TANK DEPLOYED');p.x=p.z=0;p.a=0;shots=[]}}
function gameOver(){$('#hud').classList.add('hidden');$('#pause').classList.add('hidden');$('#touch').classList.add('hidden');$('#final').textContent=`SCORE ${String(score).padStart(5,'0')} · THREAT ${stage}`;$('#gameover').classList.remove('hidden')}
function updateTraining(dt){const fireLesson=lesson===2&&keys.fireTap,ok=lesson===0&&keys.lf&&keys.rf||lesson===1&&keys.lf&&keys.rr||fireLesson;$('#leftLamp').classList.toggle('on',!!(keys.lf||keys.lr));$('#rightLamp').classList.toggle('on',!!(keys.rf||keys.rr));lessonTime=fireLesson?1.15:ok?lessonTime+dt:Math.max(0,lessonTime-dt*.5);keys.fireTap=false;$('#trainingBar').style.width=`${Math.min(100,lessonTime/1.15*100)}%`;if(lessonTime>=1.15){lesson++;lessonTime=0;tone(650,.12);if(lesson>=3)reset();else showLesson()}}
function update(dt){if(state==='training'){updateTraining(dt);return}if(state!=='play')return;const t=treadInput();move(p,t.drive,t.turn,dt);p.cool=Math.max(0,p.cool-dt);p.inv=Math.max(0,p.inv-dt);dirTimer-=dt;if(dirTimer<=0&&enemies.length){dirTimer=4;const e=enemies.reduce((a,b)=>C.distance(a,p)<C.distance(b,p)?a:b),d=C.angleDelta(p.a,Math.atan2(e.x-p.x,e.z-p.z));if(Math.abs(d)>.48)warn(`HOSTILE — ${d>0?'RIGHT':'LEFT'}`)}
for(const e of enemies){e.cool-=dt;const aim=Math.atan2(p.x-e.x,p.z-e.z),d=C.angleDelta(e.a,aim),range=C.distance(e,p);const blocked=obs.some(o=>C.segmentBox(e,p,o));move(e,range>85?.65:0,Math.sign(d)*.38,dt,e.speed);if(!blocked&&range<390&&Math.abs(d)<.1)fire(e)}
for(const m of missiles){m.life-=dt;const aim=Math.atan2(p.x-m.x,p.z-m.z),d=C.angleDelta(m.a,aim);move(m,1,Math.sign(d)*.62,dt,m.speed);if(C.distance(m,p)<18){m.life=0;hitPlayer()}}
for(const s of shots){s.px=s.x;s.pz=s.z;const nx=s.x+Math.sin(s.a)*300*dt,nz=s.z+Math.cos(s.a)*300*dt;if(obs.some(o=>C.segmentBox(s,{x:nx,z:nz},o))){s.life=0;spark(s)}else{s.x=nx;s.z=nz}s.life-=dt;if(s.owner===p){for(const e of [...enemies,...missiles])if(e.life!==0&&C.distance(s,e)<16){s.life=0;if(e.hp)e.hp--;if(!e.hp){e.dead=true;e.life=0;score+=e.type==='missile'?2000:e.type==='heavy'?3000:1000;spark(e,18);tone(62,.3,'sawtooth',.06);hud()}break}}else if(C.distance(s,p)<14){s.life=0;hitPlayer()}}
shots=shots.filter(s=>s.life>0);enemies=enemies.filter(e=>!e.dead);missiles=missiles.filter(m=>m.life>0);for(const f of fx){f.x+=f.vx*dt;f.z+=f.vz*dt;f.life-=dt}fx=fx.filter(f=>f.life>0);if(!enemies.length&&!missiles.length){stage++;spawn();warn(stage%3===0?'MISSILE APPROACHING':`THREAT LEVEL ${stage}`)}red=Math.max(0,red-dt*2);shake*=Math.pow(.03,dt)}
function spark(o,n=8){for(let i=0;i<n;i++)fx.push({x:o.x,z:o.z,vx:(Math.random()-.5)*80,vz:(Math.random()-.5)*80,life:.3+Math.random()*.7})}
function P(q){return C.project(q,p,W,H,560)}function line(a,b,c='#52ff73',w=1.5){const A=P(a),B=P(b);if(!A||!B)return;x.strokeStyle=c;x.lineWidth=w;x.beginPath();x.moveTo(A.x,A.y);x.lineTo(B.x,B.y);x.stroke()}
function grid(){for(let i=-700;i<=700;i+=55){line({x:i,z:-700},{x:i,z:700},'#0a3d19',1);line({x:-700,z:i},{x:700,z:i},'#0a3d19',1)}x.strokeStyle='#39d75a';x.beginPath();x.moveTo(0,H*.56);x.lineTo(W,H*.56);x.stroke()}
function shape(o,c='#5eff79'){const q=P(o);if(!q||q.depth>700)return;const sx=o.w*q.scale,sy=o.h*q.scale;x.strokeStyle=c;x.lineWidth=Math.max(1,q.scale*1.2);if(o.type==='pyramid'||o.type==='wedge'){const top=P({x:o.x,y:o.h,z:o.z});if(top){x.beginPath();x.moveTo(q.x-sx/2,q.y);x.lineTo(top.x,top.y);x.lineTo(q.x+sx/2,q.y);x.stroke()}}else x.strokeRect(q.x-sx/2,q.y-sy,sx,sy)}
function enemy(e){const q=P(e);if(!q||q.depth>680)return;const s=18*q.scale,c=e.type==='missile'?'#ffc657':'#ff5151';x.strokeStyle=c;x.lineWidth=Math.max(1,q.scale*1.6);x.strokeRect(q.x-s,q.y-s*.7,s*2,s*.55);x.beginPath();x.ellipse(q.x,q.y-s*.8,s*.55,s*.28,0,0,Math.PI*2);x.stroke();x.beginPath();x.moveTo(q.x,q.y-s*.8);x.lineTo(q.x+s*1.3,q.y-s*.8);x.stroke()}
function radar(){const cx=82,cy=92,r=57;x.strokeStyle='#55ff72';x.lineWidth=2;x.beginPath();x.arc(cx,cy,r,0,Math.PI*2);x.stroke();const sweep=(performance.now()/800)%(Math.PI*2);x.beginPath();x.moveTo(cx,cy);x.lineTo(cx+Math.sin(sweep)*r,cy-Math.cos(sweep)*r);x.stroke();for(const e of [...enemies,...missiles]){const dx=e.x-p.x,dz=e.z-p.z,s=Math.sin(-p.a),c=Math.cos(-p.a),rx=(dx*c-dz*s)/8,ry=-(dx*s+dz*c)/8;if(rx*rx+ry*ry<r*r){x.fillStyle=e.type==='missile'?'#ffc657':'#ff5151';x.fillRect(cx+rx-2,cy+ry-2,5,5)}}}
function sky(){x.strokeStyle='#164d25';x.lineWidth=2;x.beginPath();x.moveTo(0,336);for(let i=0;i<=12;i++){const px=i*80,py=322-Math.abs(Math.sin(i*2.17+p.a))*35;x.lineTo(px,py)}x.lineTo(W,336);x.stroke();x.strokeStyle='#70ff88';x.beginPath();x.arc(790,104,26,0,Math.PI*2);x.stroke();const pulse=2+Math.sin(performance.now()/600)*2;x.fillStyle='#62ff7a33';x.beginPath();x.arc(790,104,28+pulse,0,Math.PI*2);x.fill()}
function draw(){x.setTransform(1,0,0,1,0,0);x.fillStyle='#010603';x.fillRect(0,0,W,H);if(!p)return;x.save();if(shake>1)x.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);sky();grid();for(const o of [...obs].sort((a,b)=>C.distance(b,p)-C.distance(a,p)))shape(o);for(const e of [...enemies,...missiles])enemy(e);for(const s of shots){const q=P({x:s.x,y:6,z:s.z});if(q){x.fillStyle=s.owner===p?'#e9ff9c':'#ff5252';x.fillRect(q.x-3,q.y-3,6,6)}}for(const f of fx)shape({...f,w:2,h:2,type:'cube'},'#ffb24e');radar();x.strokeStyle='#a8ffaf';x.lineWidth=2;x.beginPath();x.moveTo(440,300);x.lineTo(472,300);x.moveTo(488,300);x.lineTo(520,300);x.moveTo(480,278);x.lineTo(480,292);x.stroke();x.restore();if(red){x.fillStyle=`rgba(255,0,0,${red*.3})`;x.fillRect(0,0,W,H)}}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function setKey(k,v){keys[k]=v}addEventListener('keydown',e=>{if([' ','arrowup','arrowdown'].includes(e.key.toLowerCase()))e.preventDefault();if(e.key.toLowerCase()==='w')setKey('lf',1);if(e.key.toLowerCase()==='s')setKey('lr',1);if(e.key==='ArrowUp')setKey('rf',1);if(e.key==='ArrowDown')setKey('rr',1);if(e.code==='Space'&&!e.repeat){keys.fireTap=true;fire(p)}if(e.key.toLowerCase()==='p')state==='paused'?resume():pause();if(e.key==='Enter'&&state==='menu')reset();if(e.key==='Escape'&&state==='training')reset();if(e.key.toLowerCase()==='r'&&state==='over')reset()});addEventListener('keyup',e=>{if(e.key.toLowerCase()==='w')setKey('lf',0);if(e.key.toLowerCase()==='s')setKey('lr',0);if(e.key==='ArrowUp')setKey('rf',0);if(e.key==='ArrowDown')setKey('rr',0)});
for(const b of document.querySelectorAll('#touch button')){const k=b.dataset.key;b.onpointerdown=e=>{e.preventDefault();if(k==='fire'){keys.fireTap=true;fire(p)}else keys[k]=1};b.onpointerup=b.onpointercancel=e=>{e.preventDefault();if(k!=='fire')keys[k]=0}}function pause(){if(state!=='play')return;state='paused';$('#paused').classList.remove('hidden')}function resume(){if(state!=='paused')return;state='play';$('#paused').classList.add('hidden');last=performance.now()}$('#play').onclick=reset;$('#start').onclick=beginTraining;$('#skip').onclick=reset;$('#restart').onclick=reset;$('#pause').onclick=pause;$('#resume').onclick=resume})();
