(()=>{'use strict';const C=window.VectorCore,cv=document.querySelector('#game'),x=cv.getContext('2d'),$=q=>document.querySelector(q),W=960,H=600,SIZE=720,SEED=1980,mobile=matchMedia('(pointer:coarse)').matches;let state='menu',p,enemies,missiles,shots,fx,obs,score,high=+(localStorage.vectorFrontlineHigh||0),stage,last=0,lastDraw=0,keys={},audio,shake=0,shakeUntil=0,red=0,lesson=0,lessonTime=0,gpFire=false,dirTimer=0,sortedObs=[];
function tone(f,d=.08,type='square',v=.03){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function generate(){const r=C.rng(SEED),a=[],types=['cube','block','pyramid','wedge','tower','cone','cylinder'];for(let i=0;i<42;i++){let o;do{o={x:(r()-.5)*1250,z:(r()-.5)*1250,w:20+r()*48,d:20+r()*48,h:14+r()*55,type:types[i%types.length]}}while(Math.hypot(o.x,o.z)<115);a.push(o)}return a}
function tankAt(dist=320){for(let n=0;n<50;n++){const a=Math.random()*Math.PI*2,e={x:p.x+Math.sin(a)*dist,z:p.z+Math.cos(a)*dist,r:14,a:a+Math.PI};if(!C.blocked(e,obs,SIZE))return e}return{x:300,z:300,r:14,a:Math.PI}}
function beginTraining(){state='training';$('#menu').classList.add('hidden');$('#training').classList.remove('hidden');lesson=0;lessonTime=0;showLesson()}
function showLesson(){const data=[['DRIVE FORWARD','Hold W and Up Arrow together.'],['PIVOT IN PLACE','Hold W and Down Arrow together.'],['FIRE CANNON','Press Space to fire forward.']][lesson];$('#lessonNum').textContent=`${lesson+1}/3`;$('#lessonTitle').textContent=data[0];$('#lessonText').textContent=data[1];$('#trainingBar').style.width='0'}
function reset(){p={x:0,z:0,r:13,a:0,reserve:2,cool:0,inv:5};obs=generate();sortedObs=obs.slice();enemies=[];missiles=[];shots=[];fx=[];score=0;stage=1;dirTimer=3;state='play';document.querySelectorAll('.panel').forEach(e=>e.classList.add('hidden'));$('#hud').classList.remove('hidden');$('#pause').classList.remove('hidden');$('#touch').classList.remove('hidden');spawn();hud();warn('HOSTILE TANK — REAR')}
function spawn(){const heavy=stage>=9&&stage%4===0,e=Object.assign(tankAt(400+Math.random()*170),{cool:Math.max(1.5,3.8-stage*.1)+Math.random()*1.5,speed:24+stage*.8,hp:heavy?2:1,type:heavy?'heavy':'tank',seenX:p.x,seenZ:p.z,scan:1.1,settle:0,turret:0,strafe:Math.random()<.5?-1:1,stuck:0,lastX:0,lastZ:0});e.turret=e.a;e.lastX=e.x;e.lastZ=e.z;enemies.push(e);if(stage>=5&&stage%4===1){enemies.length=0;const m=tankAt(480);missiles.push(Object.assign(m,{speed:48+stage*1.1,life:18,type:'missile'}))}}
function hud(){high=Math.max(high,score);localStorage.vectorFrontlineHigh=high;$('#score').textContent=String(score).padStart(5,'0');$('#high').textContent=String(high).padStart(5,'0');$('#lives').textContent='▲'.repeat(Math.max(0,p.reserve))}
function warn(s){const e=$('#warning');e.textContent=s;e.animate([{opacity:1},{opacity:1,offset:.65},{opacity:0}],{duration:1300,fill:'forwards'})}
function fire(owner,angle=owner?.a){if(!owner||owner.cool>0||state!=='play'||owner===p&&shots.some(s=>s.owner===p&&s.life>0))return;owner.cool=owner===p?.34:Math.max(1.35,3.4-stage*.08);shots.push({x:owner.x+Math.sin(angle)*18,z:owner.z+Math.cos(angle)*18,px:owner.x,pz:owner.z,a:angle,owner,life:3});if(owner===p){shake=Math.max(shake,2.5);if(navigator.vibrate)navigator.vibrate(18)}tone(owner===p?430:95,.07,owner===p?'square':'sawtooth',.045)}
function move(e,drive,turn,dt,speed=78){e.a=C.wrapAngle(e.a+turn*2.05*dt);const q={...e,x:e.x+Math.sin(e.a)*drive*speed*dt,z:e.z+Math.cos(e.a)*drive*speed*dt};if(!C.blocked(q,obs,SIZE)){e.x=q.x;e.z=q.z}}
function treadInput(){let l=(keys.lf?1:0)-(keys.lr?1:0),r=(keys.rf?1:0)-(keys.rr?1:0);const g=navigator.getGamepads?.()[0];if(g){l=Math.abs(g.axes[1]||0)>.2?-(g.axes[1]||0):l;r=Math.abs(g.axes[3]||0)>.2?-(g.axes[3]||0):r;const f=g.buttons[0]?.pressed||g.buttons[7]?.pressed;if(f&&!gpFire)fire(p);gpFire=f}return C.treadMotion(l,r)}
function hitPlayer(){if(p.inv>0)return;p.reserve--;p.inv=3.5;red=1;shake=20;shakeUntil=performance.now()+Math.min(10000,p.reserve<0?10000:1200);tone(45,.5,'sawtooth',.08);hud();if(p.reserve<0){state='over';setTimeout(gameOver,700)}else{warn('RESERVE TANK DEPLOYED');p.x=p.z=0;p.a=0;shots=[];missiles=[];for(const e of enemies)e.cool=Math.max(e.cool,3)}}
function gameOver(){$('#hud').classList.add('hidden');$('#pause').classList.add('hidden');$('#touch').classList.add('hidden');$('#final').textContent=`SCORE ${String(score).padStart(5,'0')} · THREAT ${stage}`;$('#gameover').classList.remove('hidden');setTimeout(()=>{shake=0;shakeUntil=0},Math.max(0,shakeUntil-performance.now()))}
function updateTraining(dt){const fireLesson=lesson===2&&keys.fireTap,ok=lesson===0&&keys.lf&&keys.rf||lesson===1&&keys.lf&&keys.rr||fireLesson;$('#leftLamp').classList.toggle('on',!!(keys.lf||keys.lr));$('#rightLamp').classList.toggle('on',!!(keys.rf||keys.rr));lessonTime=fireLesson?1.15:ok?lessonTime+dt:Math.max(0,lessonTime-dt*.5);keys.fireTap=false;$('#trainingBar').style.width=`${Math.min(100,lessonTime/1.15*100)}%`;if(lessonTime>=1.15){lesson++;lessonTime=0;tone(650,.12);if(lesson>=3)reset();else showLesson()}}
function update(dt){if(state==='training'){updateTraining(dt);return}if(state!=='play')return;const t=treadInput();move(p,t.drive,t.turn,dt);p.cool=Math.max(0,p.cool-dt);p.inv=Math.max(0,p.inv-dt);dirTimer-=dt;if(dirTimer<=0){dirTimer=3;if(missiles.length){const range=C.distance(missiles[0],p);warn(`MISSILE APPROACHING — ${range<170?'CLOSE':'TRACKING'}`)}else if(enemies.length){const e=enemies[0],range=C.distance(e,p),d=C.angleDelta(p.a,Math.atan2(e.x-p.x,e.z-p.z)),ad=Math.abs(d);warn(range<180&&ad<.42?'ENEMY IN RANGE':ad>2.35?'ENEMY TO REAR':d>0?'ENEMY TO RIGHT':'ENEMY TO LEFT')}}
for(const e of enemies){e.cool-=dt;e.scan-=dt;const blocked=obs.some(o=>C.segmentBox(e,p,o)),range=C.distance(e,p);if(e.scan<=0&&!blocked){e.seenX=p.x;e.seenZ=p.z;e.scan=Math.max(.48,1.45-stage*.035);e.settle=.55}const aim=Math.atan2(e.seenX-e.x,e.seenZ-e.z),bodyDelta=C.angleDelta(e.a,aim),moved=Math.hypot(e.x-e.lastX,e.z-e.lastZ);e.stuck=moved<.08?e.stuck+dt:Math.max(0,e.stuck-dt*2);if(e.stuck>.8){e.strafe*=-1;e.a=C.wrapAngle(e.a+e.strafe*1.1);e.stuck=0}e.lastX=e.x;e.lastZ=e.z;const coverNear=obs.some(o=>C.distance(o,e)<85),drive=range<115?-.45:range>245?.58:coverNear?.18:.38,turn=Math.sign(bodyDelta)*.24+e.strafe*(range<230?.22:.08);move(e,drive,turn,dt,e.speed);e.turret=C.turnToward(e.turret,aim,(e.type==='heavy'?.95:.72)*dt);const aimError=Math.abs(C.angleDelta(e.turret,aim));e.settle=aimError<.055?Math.max(0,e.settle-dt):.55;if(!blocked&&range<390&&aimError<.055&&e.settle<=0)fire(e,e.turret)}
for(const m of missiles){m.life-=dt;const aim=Math.atan2(p.x-m.x,p.z-m.z),d=C.angleDelta(m.a,aim);move(m,1,Math.sign(d)*.62,dt,m.speed);if(C.distance(m,p)<18){m.life=0;hitPlayer()}}
for(const s of shots){s.px=s.x;s.pz=s.z;const nx=s.x+Math.sin(s.a)*300*dt,nz=s.z+Math.cos(s.a)*300*dt;if(obs.some(o=>C.segmentBox(s,{x:nx,z:nz},o))){s.life=0;spark(s)}else{s.x=nx;s.z=nz}s.life-=dt;if(s.owner===p){let hit=null;for(const e of enemies)if(e.life!==0&&C.distance(s,e)<16){hit=e;break}if(!hit)for(const e of missiles)if(e.life!==0&&C.distance(s,e)<16){hit=e;break}if(hit){s.life=0;if(hit.hp)hit.hp--;if(!hit.hp){hit.dead=true;hit.life=0;score+=hit.type==='missile'?2000:hit.type==='heavy'?3000:1000;spark(hit,18);tone(62,.3,'sawtooth',.06);hud()}}}else if(C.distance(s,p)<14){s.life=0;hitPlayer()}}
shots=shots.filter(s=>s.life>0);enemies=enemies.filter(e=>!e.dead);missiles=missiles.filter(m=>m.life>0);for(const f of fx){f.x+=f.vx*dt;f.z+=f.vz*dt;f.life-=dt}fx=fx.filter(f=>f.life>0);if(!enemies.length&&!missiles.length){stage++;spawn();warn(stage%3===0?'MISSILE APPROACHING':`THREAT LEVEL ${stage}`)}red=Math.max(0,red-dt*2);shake*=Math.pow(.03,dt)}
function spark(o,n=8){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=35+Math.random()*85;fx.push({x:o.x,z:o.z,vx:Math.sin(a)*s,vz:Math.cos(a)*s,life:.45+Math.random()*.8,size:n>10?3:2})}}
function P(q){return C.project(q,p,W,H,560)}function line(a,b,c='#52ff73',w=1.5){const A=P(a),B=P(b);if(!A||!B)return;x.strokeStyle=c;x.lineWidth=w;x.beginPath();x.moveTo(A.x,A.y);x.lineTo(B.x,B.y);x.stroke()}
function grid(){for(let i=-700;i<=700;i+=55){line({x:i,z:-700},{x:i,z:700},'#0a3d19',1);line({x:-700,z:i},{x:700,z:i},'#0a3d19',1)}x.strokeStyle='#39d75a';x.beginPath();x.moveTo(0,H*.56);x.lineTo(W,H*.56);x.stroke()}
function wire(points,edges,c='#5eff79'){const q=points.map(P);x.strokeStyle=c;x.lineWidth=1.3;for(const [a,b] of edges)if(q[a]&&q[b]){x.beginPath();x.moveTo(q[a].x,q[a].y);x.lineTo(q[b].x,q[b].y);x.stroke()}}
function shape(o,c='#5eff79'){const q=P(o);if(!q||q.depth>700)return;const w=o.w/2,d=o.d/2,h=o.h;if(o.type==='cone'||o.type==='cylinder'){const top=o.type==='cone'?h:h,segments=mobile?8:12,base=[],upper=[];for(let i=0;i<segments;i++){const a=i*Math.PI*2/segments;base.push({x:o.x+Math.cos(a)*w,y:0,z:o.z+Math.sin(a)*d});upper.push({x:o.x+Math.cos(a)*(o.type==='cone'?0:w),y:h,z:o.z+Math.sin(a)*(o.type==='cone'?0:d)})}const pts=base.concat(upper),edges=[];for(let i=0;i<segments;i++){edges.push([i,(i+1)%segments],[i,i+segments]);if(o.type==='cylinder')edges.push([i+segments,(i+1)%segments+segments])}wire(pts,edges,c);return}const p=[{x:o.x-w,y:0,z:o.z-d},{x:o.x+w,y:0,z:o.z-d},{x:o.x+w,y:0,z:o.z+d},{x:o.x-w,y:0,z:o.z+d}],edges=[[0,1],[1,2],[2,3],[3,0]];if(o.type==='pyramid'){p.push({x:o.x,y:h,z:o.z});edges.push([0,4],[1,4],[2,4],[3,4])}else if(o.type==='wedge'){p.push({x:o.x-w,y:h,z:o.z+d},{x:o.x+w,y:h,z:o.z+d});edges.push([0,4],[1,5],[4,5],[2,5],[3,4])}else{p.push({x:o.x-w,y:h,z:o.z-d},{x:o.x+w,y:h,z:o.z-d},{x:o.x+w,y:h,z:o.z+d},{x:o.x-w,y:h,z:o.z+d});edges.push([4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7])}wire(p,edges,c)}
function enemy(e){const q=P(e);if(!q||q.depth>680)return;if(e.type==='missile'){const s=14*q.scale;x.strokeStyle='#ffc657';x.strokeRect(q.x-s*.35,q.y-s,s*.7,s*1.6);x.beginPath();x.moveTo(q.x-s*.8,q.y+s*.6);x.lineTo(q.x,q.y+s*.2);x.lineTo(q.x+s*.8,q.y+s*.6);x.stroke();return}const s=Math.max(5,18*q.scale),c=e.type==='heavy'?'#ff9a52':'#ff5151';x.strokeStyle=c;x.lineWidth=Math.max(1,q.scale*1.4);x.strokeRect(q.x-s,q.y-s*.45,s*2,s*.42);x.strokeRect(q.x-s*.72,q.y-s*.92,s*1.44,s*.38);x.beginPath();x.moveTo(q.x-s*1.08,q.y);x.lineTo(q.x-s*.82,q.y-s*.6);x.moveTo(q.x+s*1.08,q.y);x.lineTo(q.x+s*.82,q.y-s*.6);const rel=C.angleDelta(p.a,e.turret),barrel=s*(1.25+.2*Math.cos(rel));x.moveTo(q.x,q.y-s*.74);x.lineTo(q.x+Math.sin(rel)*barrel,q.y-s*.74-Math.cos(rel)*barrel*.25);x.stroke()}
function radar(){const cx=82,cy=92,r=57;x.strokeStyle='#55ff72';x.lineWidth=2;x.beginPath();x.arc(cx,cy,r,0,Math.PI*2);x.stroke();x.beginPath();x.moveTo(cx-12,cy-17);x.lineTo(cx,cy);x.lineTo(cx+12,cy-17);x.stroke();x.fillStyle='#baffc3';x.fillRect(cx-2,cy-2,4,4);const sweep=(performance.now()/800)%(Math.PI*2);x.globalAlpha=.65;x.beginPath();x.moveTo(cx,cy);x.lineTo(cx+Math.sin(sweep)*r,cy-Math.cos(sweep)*r);x.stroke();x.globalAlpha=1;for(const e of enemies){const q=C.radarPosition(e,p);if(q.x*q.x+q.y*q.y<r*r){x.fillStyle='#ff5151';x.fillRect(cx+q.x-3,cy+q.y-3,6,6)}}for(const e of missiles){const q=C.radarPosition(e,p);if(q.x*q.x+q.y*q.y<r*r){x.fillStyle='#ffc657';x.fillRect(cx+q.x-3,cy+q.y-3,6,6)}}}
function sky(){x.strokeStyle='#164d25';x.lineWidth=2;x.beginPath();x.moveTo(0,336);for(let i=0;i<=12;i++){const px=i*80,py=322-Math.abs(Math.sin(i*2.17+p.a))*35;x.lineTo(px,py)}x.lineTo(W,336);x.stroke();x.strokeStyle='#70ff88';x.beginPath();x.arc(790,104,26,0,Math.PI*2);x.stroke();const pulse=2+Math.sin(performance.now()/600)*2;x.fillStyle='#62ff7a33';x.beginPath();x.arc(790,104,28+pulse,0,Math.PI*2);x.fill()}
function draw(){x.setTransform(1,0,0,1,0,0);x.fillStyle='#010603';x.fillRect(0,0,W,H);if(!p)return;x.save();if(shake>1&&performance.now()<shakeUntil)x.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);else if(performance.now()>=shakeUntil)shake=0;sky();grid();for(const o of sortedObs)shape(o);for(const e of enemies)enemy(e);for(const e of missiles)enemy(e);for(const s of shots){const q=P({x:s.x,y:6,z:s.z}),tail=P({x:s.px,y:6,z:s.pz});if(q){x.strokeStyle=s.owner===p?'#e9ff9c':'#ff5252';x.lineWidth=2;if(tail){x.beginPath();x.moveTo(tail.x,tail.y);x.lineTo(q.x,q.y);x.stroke()}x.fillStyle=x.strokeStyle;x.fillRect(q.x-3,q.y-3,6,6)}}for(const f of fx)shape({x:f.x,z:f.z,w:f.size||2,h:f.size||2,type:'cube'},'#ffb24e');radar();x.strokeStyle='#a8ffaf';x.lineWidth=2;x.beginPath();x.moveTo(440,300);x.lineTo(472,300);x.moveTo(488,300);x.lineTo(520,300);x.moveTo(480,278);x.lineTo(480,292);x.stroke();x.restore();if(red){x.fillStyle=`rgba(255,0,0,${red*.3})`;x.fillRect(0,0,W,H)}}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);if(t-lastDraw>=(mobile?33:16)){if(p&&t%500<35)sortedObs.sort((a,b)=>C.distance(b,p)-C.distance(a,p));draw();lastDraw=t}requestAnimationFrame(loop)}requestAnimationFrame(loop);
function setKey(k,v){keys[k]=v}addEventListener('keydown',e=>{if([' ','arrowup','arrowdown'].includes(e.key.toLowerCase()))e.preventDefault();if(e.key.toLowerCase()==='w')setKey('lf',1);if(e.key.toLowerCase()==='s')setKey('lr',1);if(e.key==='ArrowUp')setKey('rf',1);if(e.key==='ArrowDown')setKey('rr',1);if(e.code==='Space'&&!e.repeat){keys.fireTap=true;fire(p)}if(e.key.toLowerCase()==='p')state==='paused'?resume():pause();if(e.key==='Enter'&&state==='menu')reset();if(e.key==='Escape'&&state==='training')reset();if(e.key.toLowerCase()==='r'&&state==='over')reset()});addEventListener('keyup',e=>{if(e.key.toLowerCase()==='w')setKey('lf',0);if(e.key.toLowerCase()==='s')setKey('lr',0);if(e.key==='ArrowUp')setKey('rf',0);if(e.key==='ArrowDown')setKey('rr',0)});
const touchPointers=new Map();function releaseTouch(e){const k=touchPointers.get(e.pointerId);if(!k)return;touchPointers.delete(e.pointerId);if(k!=='fire'&&![...touchPointers.values()].includes(k))keys[k]=0;e.currentTarget?.classList.remove('pressed')}for(const b of document.querySelectorAll('#touch button')){const k=b.dataset.key;b.oncontextmenu=e=>e.preventDefault();b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture?.(e.pointerId);touchPointers.set(e.pointerId,k);b.classList.add('pressed');if(k==='fire'){keys.fireTap=true;fire(p)}else keys[k]=1};b.onpointerup=b.onpointercancel=b.onlostpointercapture=releaseTouch}function clearTouch(){touchPointers.clear();for(const k of ['lf','lr','rf','rr'])keys[k]=0;document.querySelectorAll('#touch button').forEach(b=>b.classList.remove('pressed'))}addEventListener('blur',clearTouch);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTouch()});function pause(){if(state!=='play')return;clearTouch();state='paused';$('#paused').classList.remove('hidden')}function resume(){if(state!=='paused')return;state='play';$('#paused').classList.add('hidden');last=performance.now()}$('#play').onclick=reset;$('#start').onclick=beginTraining;$('#skip').onclick=reset;$('#restart').onclick=reset;$('#pause').onclick=pause;$('#resume').onclick=resume})();
