(()=>{'use strict';
const C=window.SpaceCore,canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s);
let w=0,h=0,dpr=1,state='menu',last=0,score=0,wave=1,lives=3,high=+(localStorage.spaceDefenderHigh||0),ship,asteroids=[],shots=[],enemyShots=[],particles=[],stars=[],keys={},audio,shotClock=0,respawn=0,waveDelay=0,ufo=null,ufoTimer=7;
function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);stars=Array.from({length:Math.min(180,(w*h/6000)|0)},()=>({x:Math.random()*w,y:Math.random()*h,z:.2+Math.random()*.8,s:Math.random()*2}))}addEventListener('resize',resize);resize();
function makeShip(){return{x:w/2,y:h/2,vx:0,vy:0,a:-Math.PI/2,r:13,inv:2.2}}
function asteroid(size=3,x,y){const edge=(Math.random()*4)|0,pad=55;if(x==null){x=edge%2?Math.random()*w:(edge? w+pad:-pad);y=edge%2?(edge===1?-pad:h+pad):Math.random()*h}const speed=35+wave*7+Math.random()*45,a=Math.atan2(h/2-y,w/2-x)+(Math.random()-.5)*1.4;return{x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,size,r:size===3?42:size===2?25:14,spin:Math.random()*C.TAU,rot:0,vr:(Math.random()-.5)*1.5,shape:Array.from({length:10},()=>.78+Math.random()*.35)}}
function start(){score=0;wave=1;lives=3;asteroids=[];shots=[];enemyShots=[];particles=[];ufo=null;ufoTimer=6;ship=makeShip();state='playing';respawn=0;waveDelay=0;$('.panel:not(.hidden)')?.classList.add('hidden');$('#hud').classList.remove('hidden');$('#pause').classList.remove('hidden');$('#touch').classList.remove('hidden');spawnWave();updateHud();last=performance.now();tone(220,.15,'sawtooth')}
function spawnWave(){for(let i=0;i<C.waveAsteroids(wave);i++)asteroids.push(asteroid(3));banner(`WAVE ${wave}`)}
function banner(t){const e=$('#waveBanner');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1200)}
function tone(f,d=.05,type='square',vol=.035){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function fire(){if(shotClock>0||!ship||respawn>0)return;shotClock=.16;shots.push({x:ship.x+Math.cos(ship.a)*18,y:ship.y+Math.sin(ship.a)*18,vx:ship.vx+Math.cos(ship.a)*520,vy:ship.vy+Math.sin(ship.a)*520,r:2,life:1.15});tone(680,.06,'square',.025)}
function burst(x,y,color='#70f8ff',n=15){for(let i=0;i<n;i++){const a=Math.random()*C.TAU,s=30+Math.random()*170;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.65,color})}}
function destroy(a,award=true){if(award)score+=C.scoreFor(a.size);asteroids.splice(asteroids.indexOf(a),1);for(const spec of C.splitSpec(a))asteroids.push({...spec,shape:Array.from({length:10},()=>.78+Math.random()*.35)});burst(a.x,a.y,a.size===1?'#ffcf68':'#9d70ff',10+a.size*6);tone(90+a.size*35,.15,'sawtooth',.045);if(score>high){high=score;localStorage.spaceDefenderHigh=high}updateHud()}
function spawnUfo(){const fromLeft=Math.random()<.5;ufo={x:fromLeft?-35:w+35,y:70+Math.random()*(h-140),vx:(fromLeft?1:-1)*(105+wave*4),vy:(Math.random()-.5)*35,r:18,fire:.7+Math.random()*.8};tone(280,.18,'sine',.035)}
function destroyUfo(){if(!ufo)return;score+=500;burst(ufo.x,ufo.y,'#ff4f91',30);tone(110,.35,'sawtooth',.06);ufo=null;ufoTimer=9+Math.random()*7;if(score>high){high=score;localStorage.spaceDefenderHigh=high}updateHud()}
function hitShip(){if(ship.inv>0||respawn>0)return;lives--;burst(ship.x,ship.y,'#ff4f91',35);tone(55,.5,'sawtooth',.07);updateHud();if(lives<=0){state='gameover';setTimeout(showGameOver,650)}else{respawn=1.4;ship=makeShip();ship.inv=3}}
function update(dt){shotClock=Math.max(0,shotClock-dt);if(respawn>0)respawn-=dt;if(keys.left||keys.ArrowLeft||keys.a)ship.a-=3.7*dt;if(keys.right||keys.ArrowRight||keys.d)ship.a+=3.7*dt;const thrust=keys.thrust||keys.ArrowUp||keys.w;if(thrust){ship.vx+=Math.cos(ship.a)*250*dt;ship.vy+=Math.sin(ship.a)*250*dt;if(Math.random()<.6)particles.push({x:ship.x-Math.cos(ship.a)*14,y:ship.y-Math.sin(ship.a)*14,vx:-Math.cos(ship.a)*90+(Math.random()-.5)*35,vy:-Math.sin(ship.a)*90+(Math.random()-.5)*35,life:.25,color:'#54f7ff'})}if(keys.fire||keys[' '])fire();ship.vx*=Math.pow(.992,dt*60);ship.vy*=Math.pow(.992,dt*60);const sp=Math.hypot(ship.vx,ship.vy);if(sp>330){ship.vx*=330/sp;ship.vy*=330/sp}ship.x=C.wrap(ship.x+ship.vx*dt,w);ship.y=C.wrap(ship.y+ship.vy*dt,h);ship.inv=Math.max(0,ship.inv-dt);
for(const a of asteroids){a.x=C.wrap(a.x,w);a.y=C.wrap(a.y,h);a.x+=a.vx*dt;a.y+=a.vy*dt;a.rot+=a.vr*dt;if(C.collides(ship,a,-3))hitShip()}
for(const s of shots){s.x=C.wrap(s.x,w);s.y=C.wrap(s.y,h);s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(ufo&&C.collides(s,ufo)){s.life=0;destroyUfo();continue}for(const a of [...asteroids])if(C.collides(s,a)){s.life=0;destroy(a);break}}shots=shots.filter(s=>s.life>0);
ufoTimer-=dt;if(!ufo&&ufoTimer<=0)spawnUfo();if(ufo){ufo.x+=ufo.vx*dt;ufo.y=C.wrap(ufo.y+ufo.vy*dt,h);ufo.fire-=dt;if(ufo.fire<=0){const a=Math.atan2(ship.y-ufo.y,ship.x-ufo.x)+(Math.random()-.5)*Math.max(.08,.45-wave*.025);enemyShots.push({x:ufo.x,y:ufo.y,vx:Math.cos(a)*260,vy:Math.sin(a)*260,r:3,life:3});ufo.fire=Math.max(.55,1.5-wave*.04);tone(340,.08,'square',.025)}if(ufo.x<-70||ufo.x>w+70){ufo=null;ufoTimer=8+Math.random()*8}}
for(const s of enemyShots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(C.collides(s,ship)){s.life=0;hitShip();continue}for(const a of [...asteroids])if(C.collides(s,a)){s.life=0;destroy(a,false);break}}enemyShots=enemyShots.filter(s=>s.life>0&&s.x>-20&&s.x<w+20&&s.y>-20&&s.y<h+20);
for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;p.vx*=.98;p.vy*=.98}particles=particles.filter(p=>p.life>0);
if(!asteroids.length&&!waveDelay)waveDelay=1.6;if(waveDelay){waveDelay-=dt;if(waveDelay<=0){waveDelay=0;wave++;ship.inv=Math.max(ship.inv,2);spawnWave();updateHud()}}
}
function draw(){ctx.clearRect(0,0,w,h);const t=performance.now()*.001;for(const s of stars){const x=C.wrap(s.x-t*8*s.z,w),y=s.y;ctx.fillStyle=`rgba(160,210,255,${.25+s.z*.65})`;ctx.fillRect(x,y,s.s*s.z,s.s*s.z)}ctx.strokeStyle='#26345b55';ctx.lineWidth=1;for(let x=0;x<w;x+=80){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=80){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}
for(const a of asteroids){ctx.save();ctx.translate(a.x,a.y);ctx.rotate(a.rot);ctx.beginPath();for(let i=0;i<a.shape.length;i++){const q=i/a.shape.length*C.TAU,r=a.r*a.shape[i];i?ctx.lineTo(Math.cos(q)*r,Math.sin(q)*r):ctx.moveTo(Math.cos(q)*r,Math.sin(q)*r)}ctx.closePath();ctx.fillStyle='#11162b';ctx.strokeStyle=a.size===1?'#ffcf68':'#9c83d8';ctx.lineWidth=2;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=9;ctx.fill();ctx.stroke();ctx.restore()}
ctx.fillStyle='#8dfcff';ctx.shadowColor='#54f7ff';ctx.shadowBlur=12;for(const s of shots){ctx.beginPath();ctx.arc(s.x,s.y,2.4,0,C.TAU);ctx.fill()}ctx.shadowBlur=0;
ctx.fillStyle='#ff5d9b';ctx.shadowColor='#ff4f91';ctx.shadowBlur=12;for(const s of enemyShots){ctx.beginPath();ctx.arc(s.x,s.y,3.2,0,C.TAU);ctx.fill()}ctx.shadowBlur=0;
if(ufo){ctx.save();ctx.translate(ufo.x,ufo.y);ctx.strokeStyle='#ff6ba5';ctx.fillStyle='#25132d';ctx.lineWidth=2.5;ctx.shadowColor='#ff4f91';ctx.shadowBlur=14;ctx.beginPath();ctx.ellipse(0,3,22,8,0,0,C.TAU);ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(0,-3,10,0,Math.PI,true);ctx.stroke();ctx.beginPath();ctx.moveTo(-25,3);ctx.lineTo(25,3);ctx.stroke();ctx.restore()}
for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,2.5,2.5)}ctx.globalAlpha=1;
if(ship&&state!=='gameover'&&respawn<=0&&!(ship.inv>0&&Math.floor(t*10)%2)){ctx.save();ctx.translate(ship.x,ship.y);ctx.rotate(ship.a);ctx.strokeStyle='#54f7ff';ctx.fillStyle='#0c1830';ctx.lineWidth=2.5;ctx.shadowColor='#54f7ff';ctx.shadowBlur=13;ctx.beginPath();ctx.moveTo(18,0);ctx.lineTo(-12,-11);ctx.lineTo(-7,0);ctx.lineTo(-12,11);ctx.closePath();ctx.fill();ctx.stroke();if(keys.thrust||keys.ArrowUp||keys.w){ctx.strokeStyle='#ff4f91';ctx.beginPath();ctx.moveTo(-8,-5);ctx.lineTo(-22,0);ctx.lineTo(-8,5);ctx.stroke()}ctx.restore()}}
function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;if(state==='playing')update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function updateHud(){$('#score').textContent=String(score).padStart(6,'0');$('#high').textContent=String(high).padStart(6,'0');$('#wave').textContent=wave;$('#lives').textContent='◆'.repeat(Math.max(0,lives))||'—'}
function pause(){if(state!=='playing')return;state='paused';$('#paused').classList.remove('hidden')}function resume(){if(state!=='paused')return;state='playing';$('#paused').classList.add('hidden');last=performance.now()}
function showGameOver(){$('#hud').classList.add('hidden');$('#pause').classList.add('hidden');$('#touch').classList.add('hidden');$('#finalScore').textContent=score;$('#record').textContent=score>=high?'NEW SECTOR RECORD':'';$('#gameover').classList.remove('hidden')}
addEventListener('keydown',e=>{if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();keys[e.key]=true;keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='p')state==='paused'?resume():pause();if(e.key==='Escape'&&state==='paused')resume()});addEventListener('keyup',e=>{keys[e.key]=false;keys[e.key.toLowerCase()]=false});
for(const b of document.querySelectorAll('[data-key]')){const k=b.dataset.key,on=e=>{e.preventDefault();keys[k]=true;if(k==='fire')fire()},off=e=>{e.preventDefault();keys[k]=false};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off)}
$('#start').onclick=start;$('#restart').onclick=start;$('#restartPause').onclick=start;$('#pause').onclick=pause;$('#resume').onclick=resume;updateHud();
})();
