(()=>{'use strict';
const C=window.GraveCore,canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),frame=document.querySelector('.frame');ctx.imageSmoothingEnabled=false;
const W=320,H=180,STEP=20;let state='title',last=0,acc=0,tick=0,camera=0,score=0,checkpoint=36,keys={},pressed={},audio=null;
const solids=[
 {x:0,y:151,w:420,h:29},{x:455,y:151,w:230,h:29},{x:720,y:151,w:240,h:29},{x:995,y:151,w:405,h:29},
 {x:125,y:123,w:45,h:8},{x:208,y:106,w:54,h:8},{x:315,y:128,w:60,h:8},{x:474,y:118,w:60,h:8},{x:580,y:91,w:52,h:8},
 {x:755,y:122,w:65,h:8},{x:850,y:95,w:56,h:8},{x:1010,y:124,w:55,h:8},{x:1115,y:105,w:70,h:8},{x:1245,y:126,w:65,h:8}
];
const ladders=[{x:230,y:106,w:10,h:45},{x:598,y:91,w:10,h:60},{x:872,y:95,w:10,h:56},{x:1142,y:105,w:10,h:46}];
const player={x:36,y:125,w:12,h:26,vx:0,vy:0,jumpVx:0,grounded:false,armoured:true,lives:3,invuln:0,state:'alive',deathTimer:0,fireCd:0,face:1,crouch:false,onLadder:false};
let enemies=[],bolts=[],enemyBolts=[],particles=[],platform,boss,portal,toast='';let toastTime=0;
function enemy(type,x,y){const defs={risen:[12,18,2],thorn:[16,18,3],wing:[16,10,2],charger:[20,28,6]};const d=defs[type];return{type,x,y,w:d[0],h:d[1],hp:d[2],vx:0,vy:0,t:Math.floor(x)%80,alive:true,emerge:type==='risen'?55:0,face:-1};}
function reset(full=true){if(full){score=0;checkpoint=36;player.lives=3;}Object.assign(player,{x:checkpoint,y:110,vx:0,vy:0,jumpVx:0,armoured:true,invuln:50,state:'alive',deathTimer:0,fireCd:0,face:1});
 enemies=[enemy('risen',165,133),enemy('thorn',340,133),enemy('wing',465,68),enemy('risen',548,133),enemy('thorn',650,133),enemy('wing',770,62),enemy('charger',900,123),enemy('risen',1040,133),enemy('thorn',1165,133)];
 bolts=[];enemyBolts=[];particles=[];platform={x:676,y:125,w:42,h:7,dir:1};boss=enemy('charger',1280,113);boss.w=26;boss.h=38;boss.hp=16;boss.maxHp=16;boss.boss=true;portal={x:1350,y:108,w:26,h:43,open:false};camera=C.clamp(player.x-80,0,1080);toast='FIND THE DAWN SEAL';toastTime=110;}
function snd(kind){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);const now=audio.currentTime;const p={fire:[660,.06,'square'],hit:[150,.14,'sawtooth'],jump:[280,.08,'square'],armour:[90,.24,'sawtooth'],death:[70,.5,'square'],key:[880,.45,'triangle'],step:[110,.04,'square']}[kind];o.type=p[2];o.frequency.setValueAtTime(p[0],now);if(kind==='key')o.frequency.exponentialRampToValueAtTime(1320,now+p[1]);else o.frequency.exponentialRampToValueAtTime(Math.max(35,p[0]/2),now+p[1]);g.gain.setValueAtTime(.055,now);g.gain.exponentialRampToValueAtTime(.001,now+p[1]);o.start();o.stop(now+p[1]);}catch{}}
function burst(x,y,color,n=12){for(let i=0;i<n;i++){const a=i/n*Math.PI*2;particles.push({x,y,vx:Math.cos(a)*(Math.random()*1.8+.4),vy:Math.sin(a)*(Math.random()*1.8+.4),life:25+Math.random()*18,color});}}
function hurt(){const result=C.applyHit(player);if(result==='ignored')return;if(result==='armour'){snd('armour');burst(player.x+6,player.y+9,'#f8df9e',18);frame.classList.add('shake');setTimeout(()=>frame.classList.remove('shake'),250);toast='ARMOUR SHATTERED';toastTime=70;}else{snd('death');burst(player.x+6,player.y+8,'#ff6347',28);frame.classList.add('shake');setTimeout(()=>frame.classList.remove('shake'),250);}}
function respawn(){if(player.lives<=0){showOverlay('QUEST ENDED',`Score ${score.toString().padStart(6,'0')}`,'gameover');return;}Object.assign(player,{x:checkpoint,y:100,vx:0,vy:0,state:'alive',armoured:true,invuln:90});}
function shoot(){if(player.fireCd||bolts.filter(b=>b.alive).length>=3||player.state!=='alive')return;player.fireCd=14;bolts.push({x:player.x+(player.face>0?13:-1),y:player.y+(player.crouch?18:9),vx:player.face*3.3,r:2,life:105,alive:true});snd('fire');for(let i=0;i<5;i++)particles.push({x:player.x+(player.face>0?14:0),y:player.y+9,vx:player.face*(.5+Math.random()),vy:(Math.random()-.5),life:8,color:'#ffcf73'});}
function updatePlayer(){if(player.state==='dead'){if(--player.deathTimer<=0)respawn();return;}if(player.invuln>0)player.invuln--;if(player.fireCd>0)player.fireCd--;const left=keys.left||keys.KeyA||keys.ArrowLeft,right=keys.right||keys.KeyD||keys.ArrowRight,down=keys.down||keys.KeyS||keys.ArrowDown,up=keys.jump||keys.KeyW||keys.ArrowUp||keys.KeyZ;
 const ladder=ladders.find(l=>C.overlap(player,l));player.onLadder=!!ladder&&(up||down||player.onLadder);player.crouch=!!down&&player.grounded;
 if(player.onLadder){player.vy=(down?1:0)-(up?1:0);player.vx=0;if(ladder)player.x+=(ladder.x+ladder.w/2-(player.x+player.w/2))*.25;if(!ladder)player.onLadder=false;}else{if(player.grounded){player.vx=(right?1.25:0)-(left?1.25:0);if(player.vx)player.face=Math.sign(player.vx);}else player.vx=player.jumpVx;player.vy=Math.min(player.vy+.19,4.6);}
 if((pressed.jump||pressed.KeyW||pressed.ArrowUp||pressed.KeyZ)&&player.grounded&&!down){const dir=left?-1:right?1:player.face;C.fixedJump(player,dir);player.vx=player.jumpVx;snd('jump');}
 if(pressed.fire||pressed.Space||pressed.KeyX)shoot();if(player.crouch)player.vx=0;
 const movingSolids=solids.concat(platform);C.moveAndCollide(player,player.vx,player.vy,movingSolids);player.x=C.clamp(player.x,0,1388-player.w);if(player.y>190)hurt();
 if(player.x>740&&checkpoint<738){checkpoint=738;toast='EMBER MARK LIT';toastTime=100;snd('key');}
 for(const e of enemies.concat(boss.alive?[boss]:[]))if(e.alive&&C.overlap(player,e))hurt();for(const b of enemyBolts)if(C.projectileHit(b,player)){b.alive=false;hurt();}
}
function updateEnemy(e){if(!e.alive)return;e.t++;e.face=player.x<e.x?-1:1;if(e.emerge>0){e.emerge--;return;}if(e.type==='risen'){e.vx=e.face*.28;if(e.t%170===0)e.vy=-2.4;}else if(e.type==='thorn'){e.vx=0;if(e.t%95===0){const dx=player.x-e.x,dy=player.y-e.y,d=Math.hypot(dx,dy)||1;enemyBolts.push({x:e.x+8,y:e.y+5,vx:dx/d*1.55,vy:dy/d*1.55,r:2,life:180,alive:true});}}else if(e.type==='wing'){e.vx=e.face*.62;e.vy=Math.sin(e.t*.08)*.55;}else if(e.type==='charger'){const near=Math.abs(player.x-e.x)<145;e.vx=e.face*(near?(e.boss?1.05:1.45):.22);if(e.boss&&e.t%82===0){for(const a of [-.35,0,.35])enemyBolts.push({x:e.x+12,y:e.y+8,vx:e.face*1.5,vy:a,r:3,life:160,alive:true});}}
 if(e.type==='wing'){e.x+=e.vx;e.y+=e.vy;}else{e.vy=Math.min(e.vy+.18,4);C.moveAndCollide(e,e.vx,e.vy,solids.concat(platform));}
}
function updateProjectiles(){for(const b of bolts){b.x+=b.vx;b.life--;if(b.life<=0||solids.some(s=>b.x>s.x&&b.x<s.x+s.w&&b.y>s.y&&b.y<s.y+s.h))b.alive=false;for(const e of enemies.concat(boss.alive?[boss]:[]))if(e.alive&&C.projectileHit(b,e)){b.alive=false;e.hp--;snd('hit');burst(b.x,b.y,'#69d1c5',5);if(e.hp<=0){e.alive=false;score+=e.boss?2500:({risen:100,thorn:200,wing:250,charger:500}[e.type]);burst(e.x+e.w/2,e.y+e.h/2,e.boss?'#ffcf73':'#d65e6c',e.boss?35:14);if(e.boss){portal.open=true;toast='THE DAWN SEAL AWAKENS';toastTime=130;snd('key');}}break;}}
 for(const b of enemyBolts){b.x+=b.vx;b.y+=b.vy;b.life--;if(b.life<=0)b.alive=false;}bolts=bolts.filter(b=>b.alive);enemyBolts=enemyBolts.filter(b=>b.alive);
}
function update(){if(state!=='play')return;tick++;platform.x+=platform.dir*.45;if(platform.x>714||platform.x<670)platform.dir*=-1;updatePlayer();enemies.forEach(updateEnemy);updateEnemy(boss);updateProjectiles();for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.05;p.life--;}particles=particles.filter(p=>p.life>0);if(toastTime>0)toastTime--;camera+=((C.clamp(player.x-95,0,1080))-camera)*.12;if(portal.open&&C.overlap(player,portal)){score+=5000;showOverlay('DAWN RESTORED',`The Briar Warden falls. Final score ${score.toString().padStart(6,'0')}`,'win');snd('key');}pressed={};}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x-camera),Math.round(y),w,h)}
function text(t,x,y,c='#f8df9e',align='left'){ctx.fillStyle=c;ctx.font='7px monospace';ctx.textAlign=align;ctx.fillText(t,x,y)}
function drawBackground(){const grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#15142d');grad.addColorStop(1,'#40223a');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);ctx.fillStyle='#eee0b5';ctx.beginPath();ctx.arc(265-camera*.035,31,15,0,Math.PI*2);ctx.fill();ctx.fillStyle='#15142d';ctx.beginPath();ctx.arc(271-camera*.035,27,14,0,Math.PI*2);ctx.fill();for(let i=0;i<20;i++)rect((i*83)%1400,30+(i*19)%55,2,2,'#a6a0c4');for(let i=0;i<30;i++){const x=i*52-camera*.2;ctx.fillStyle='#1d1830';ctx.beginPath();ctx.moveTo(x,151);ctx.lineTo(x+22,85+(i%4)*8);ctx.lineTo(x+43,151);ctx.fill();}for(let x=0;x<1400;x+=46){rect(x,142-(x%3)*4,4,9,'#4c4153');rect(x-4,141-(x%3)*4,12,3,'#4c4153');}}
function drawWorld(){for(const s of solids){rect(s.x,s.y,s.w,s.h,'#4d3e55');rect(s.x,s.y,s.w,3,'#8f6f65');for(let x=s.x+4;x<s.x+s.w;x+=14)rect(x,s.y+7,8,3,'#372d43');}for(const l of ladders){for(let y=l.y;y<l.y+l.h;y+=7){rect(l.x,y,l.w,2,'#c28c65')}rect(l.x,l.y,2,l.h,'#8c654f');rect(l.x+l.w-2,l.y,2,l.h,'#8c654f');}rect(platform.x,platform.y,platform.w,platform.h,'#69d1c5');rect(738,126,4,25,'#ff8a5b');if(portal.open){rect(portal.x,portal.y,portal.w,portal.h,'#69d1c5');rect(portal.x+5,portal.y+5,portal.w-10,portal.h-5,'#281d3a');}else{rect(portal.x,portal.y,portal.w,portal.h,'#48374f');}}
function drawEntity(e){if(!e.alive)return;let c={risen:'#85a36b',thorn:'#c25b69',wing:'#b49bd4',charger:'#dc784f'}[e.type];const y=e.y+(e.emerge>0?Math.max(0,e.h-e.emerge/3):0);rect(e.x,y,e.w,e.y+e.h-y,c);if(e.emerge<=0){rect(e.x+(e.face>0?e.w-4:2),y+4,2,2,'#ffe46b');if(e.type==='wing'){rect(e.x-5,y+2,6,4,c);rect(e.x+e.w-1,y+2,6,4,c);}}}
function drawPlayer(){if(player.state==='dead'||(player.invuln>0&&tick%6<3))return;const h=player.crouch?17:player.h,y=player.y+player.h-h;rect(player.x,y,player.w,h,player.armoured?'#d7d4c8':'#de765d');rect(player.x+2,y-4,8,6,player.armoured?'#8f97a2':'#b95a51');rect(player.x+(player.face>0?9:1),y-2,2,2,'#ffcf73');rect(player.x+(player.face>0?9:-3),y+8,6,3,'#69d1c5');}
function render(){drawBackground();drawWorld();enemies.forEach(drawEntity);drawEntity(boss);for(const b of bolts)rect(b.x-2,b.y-1,5,3,'#69d1c5');for(const b of enemyBolts)rect(b.x-b.r,b.y-b.r,b.r*2,b.r*2,'#ff6b4a');for(const p of particles)rect(p.x,p.y,2,2,p.color);drawPlayer();ctx.fillStyle='#100d19dd';ctx.fillRect(0,0,W,14);text(`SCORE ${score.toString().padStart(6,'0')}`,6,10);text(`LIVES ${Math.max(0,player.lives)}  ${player.armoured?'ARMOUR':'EXPOSED'}`,314,10,player.armoured?'#b9d8dc':'#ff846b','right');if(boss.alive&&player.x>1100){ctx.fillStyle='#211628';ctx.fillRect(88,19,144,7);ctx.fillStyle='#d65e6c';ctx.fillRect(90,21,140*(boss.hp/boss.maxHp),3);text('BRIAR WARDEN',160,34,'#ffcf73','center');}if(toastTime>0){ctx.fillStyle='#100d19dd';ctx.fillRect(78,150,164,15);text(toast,160,160,'#ffcf73','center');}}
function loop(t){const dt=Math.min(80,t-last);last=t;acc+=dt;while(acc>=STEP){update();acc-=STEP;}render();requestAnimationFrame(loop)}
function start(){reset(true);state='play';document.querySelector('#title').classList.add('hidden');document.querySelector('#overlay').classList.add('hidden');audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();}
function showOverlay(title,body,kind='pause'){state=kind;document.querySelector('#overlayTitle').textContent=title;document.querySelector('#overlayText').textContent=body;document.querySelector('#overlayKicker').textContent=kind==='win'?'QUEST COMPLETE':kind==='gameover'?'THE WILDS CLAIM YOU':'A MOMENT OF SILENCE';document.querySelector('#resume').textContent=kind==='pause'?'RESUME':'PLAY AGAIN';document.querySelector('#overlay').classList.remove('hidden');}
function togglePause(){if(state==='play')showOverlay('PAUSED','The burial wilds wait.','pause');else if(state==='pause'){state='play';document.querySelector('#overlay').classList.add('hidden');}}
const map={KeyA:'KeyA',KeyD:'KeyD',KeyS:'KeyS',KeyW:'KeyW',ArrowLeft:'ArrowLeft',ArrowRight:'ArrowRight',ArrowDown:'ArrowDown',ArrowUp:'ArrowUp',KeyZ:'KeyZ',KeyX:'KeyX',Space:'Space'};
addEventListener('keydown',e=>{if(map[e.code]){if(!keys[map[e.code]])pressed[map[e.code]]=true;keys[map[e.code]]=true;e.preventDefault();}if((e.code==='KeyP'||e.code==='Escape')&&state!=='title')togglePause();});addEventListener('keyup',e=>{if(map[e.code])keys[map[e.code]]=false;});
document.querySelector('#start').onclick=start;document.querySelector('#resume').onclick=()=>{if(state==='pause')togglePause();else start();};document.querySelector('#restart').onclick=start;
document.querySelectorAll('#touch button').forEach(b=>{const k=b.dataset.key;const on=e=>{e.preventDefault();if(!keys[k])pressed[k]=true;keys[k]=true;};const off=e=>{e.preventDefault();keys[k]=false;};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off);});
reset(true);requestAnimationFrame(loop);
})();
